if: tag IS blank

language: java

sudo: false

jdk:
  - openjdk11

install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install fakeroot; fi
  - chmod a+x ./gradlew

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew --info --stacktrace -Ddownload.jpackage=true jpackage
