if: tag IS blank

language: java

sudo: false

jdk:
  - openjdk11

before_install:
  - wget $JPACKAGE_DOWNLOAD_URL

install:
  - chmod a+x ./gradlew
  - pwd
  - ls -al
  - gunzip -c $JPACKAGE_ARCHIVE_NAME | tar xopf -
  - ls -al

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew --info --stacktrace -Ddownload.jpackage=true jpackage
